# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

default: &default
  adapter: postgresql
  user: sample_app
  password: 123
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: sample_app_db

test:
  <<: *default
  database: sample_app_db

production:
  <<: *default
  database: sample_app_db


